# goal definition
# goal can be either handle name or goal configuration
string handle_name
bool do_plan
bool do_insertion
---
# result definition
string error_msg
---
# feedback definition
# Progress from 0.0 to 1.0 on how much of the path was already executed
bool planing
float64 progress
